### ISSUE TITLE
Error collecting wtih `ad`, `dns`, and `dhcp`

### ISSUE THREAD

**Issue by kvietcong** [prometheus-community/windows_exporter#1019]
Hi I'm currently attempting to run Windows Exporter v0.18.1 on Windows Server 2012 R2 and am currently getting these errors upon the ad, dns, and dhcp servers. I was wondering if I could get any help with this?

Error Logs
```
msg="failed collecting ad metrics:<nil> Exception occurred. (Invalid class )" source="ad.go:460"
msg="collector ad failed after 0.143120s: Exception occurred. (Invalid class )" source="exporter.go:207"
msg="failed collecting dns metrics:<nil> Exception occurred. (Invalid class )" source="dns.go:187"
msg="collector dns failed after 0.147124s: Exception occurred. (Invalid class )" source="exporter.go:207"
msg="collector dhcp failed after 0.000000s: counter not found" source="exporter.go:207"
msg="failed collecting dns metrics:<nil> Exception occurred. (Invalid class )" source="dns.go:187"
msg="collector dns failed after 0.006006s: Exception occurred. (Invalid class )" source="exporter.go:207"
```

config.yaml
```yaml
collectors:
  enabled: logical_disk,tcp,process,service,dhcp,cpu,cpu_info,cs,net,system,textfile,memory,os,ad,dns
collector:
  process:
  service:
log:
  level: error
telemetry:
  addr: ":6060"
  path: /metrics
```

Scrape Configuration
```yaml
  - job_name: windows_exporter
    static_configs:
    - targets:
      - "myhost:6060"
```
