### ISSUE TITLE
Failed collecting iis metrics - windows node exporter 

### ISSUE THREAD

**Issue by Amikh** [prometheus-community/windows_exporter#1105]
Hi, can't getting  metrics from `iis`
 The error:   
` level=error msg="failed collecting iis metrics:<nil> counter not found" source="iis.go:824"` 
use latest version image 
`image: mcr.microsoft.com/windows/nanoserver:1809`
 with config map 
```
 config.yml: |
    collectors:
      enabled: cpu,cs,logical_disk,net,os,service,system,iis,container
    collector:
      service:
        services-where: Name='windows_exporter'
```
another metrics can getting and can to see in the Prometheus

![image](https://user-images.githubusercontent.com/8455912/207854036-400466e8-2b24-4a49-a3cb-b9abd1b99397.png)
