### ISSUE TITLE
How can I get the username from a process?

### ISSUE THREAD

**Issue by marco-carvalho** [prometheus-community/windows_exporter#1125]
Right now I'm using this `config.file`:
```
collectors:
  enabled: cpu,cpu_info,cs,logical_disk,memory,net,os,service,system,process,iis
collector:
  service:
    services-where: "Name='W3SVC' OR  Name='AppHostSVC' OR Name='IISADMIN' OR Name='MSFTPSVC' OR Name='MWMSVC' OR Name='WAS' OR Name='FTPSVC'"
  logical_disk:
    volume-blacklist: "HarddiskVolume. |harddiskvolume. "
  process:
    whitelist: "^w3wp|^W3WP"
log:
  level: warn
```

In my grafana, at the `Metrics browser` I'm using `windows_process_working_set_bytes`:
![image](https://user-images.githubusercontent.com/15821724/214404899-66807b15-aef2-4e53-a460-043b09729630.png)

And I'm getting this table:
![image](https://user-images.githubusercontent.com/15821724/214405119-c572ee39-9d27-4c98-8b48-c4b42b19da2c.png)

The memory results are all correct, but I wish to see this username on the row label of the table:
![image](https://user-images.githubusercontent.com/15821724/214405479-77857749-2eb1-4844-bfd8-58174c990a7b.png)

Can somebody help me, please?
