### ISSUE TITLE
Environment Variable in args not being used Kubernetes

### ISSUE THREAD

**Issue by mglazenborg** [prometheus-community/windows_exporter#1182]
I have been working on setting up a Helm chart for the Windows Exporter and I'm currently running into an issue where an environment variable is not being used. This variable is either set to 0.0.0.0 or to a fieldRef refering to the hostIP depending on a value.

### The issue

From the Helm chart I get the following manifest (removed irrelevant sections).

```yaml
securityContext:
  windowsOptions:
    hostProcess: true
    runAsUserName: NT AUTHORITY\system
containers:
  - name: windows-exporter
    image: ghcr.io/prometheus-community/windows-exporter:v0.22.0
    imagePullPolicy: IfNotPresent
    args:
      - --web.listen-address=[%HOST_IP%]:9182
      - --collectors.enabled=[defaults],container
    env:
      - name: HOST_IP
        value: "0.0.0.0"
hostNetwork: true
```

Deploying this manifest returns the following error
`level=fatal msg="cannot start windows_exporter: listen tcp: lookup %HOST_IP%: no such host" source="exporter.go:426"`

When an IP is used in the arg instead of the variable the container runs without issue. Manually executing the windows_exporter.exe with the args listed above inside of the container doesn't result in this issue. 

### Things I've tried
Using the powershell variable formatting `$env:HOST_IP`.
I've verified that `--config.file=%CONTAINER_SANDBOX_MOUNT_POINT%/config.yml` from the [example](https://github.com/prometheus-community/windows_exporter/blob/master/kubernetes/windows-exporter-daemonset.yaml) works, meaning that it does use cmd style variables, with the difference being that `%CONTAINER_SANDBOX_MOUNT_POINT%` is in the container by default.
