### ISSUE TITLE
Grafana doesnt show data from Windows Exporter

### ISSUE THREAD

**Issue by joaquinsusin** [prometheus-community/windows_exporter#1223]
Hey so I have 2 ec2 instances one is a Prometheus Server with Grafana and the other one is a Windows client with windows exporter, the problem is that when I enter on prometheus and query something like windows_cpu_core_frequency_mhz I see results displaying but when I enter on grafana and add a source of prometheus with http://XX.XX.XX.XX:9182 it says Data source is working but when I try to display anything it says no data.

prometheus.yml
```yaml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090", "13.38.53.12:9182"]

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'windows_exporter'
    static_configs:
      - targets: ['13.38.53.12:9182']`
```

docker-compose.yml
```yaml
version: "3.9"
services:
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-configs:/etc/grafana
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - prom-data:/prometheus
      - prom-configs:/etc/prometheus
  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude'
      - '^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'

volumes:
  grafana-data:
  grafana-configs:
  prom-data:
  prom-configs:
```
