### ISSUE TITLE
process colector doesn't load include or excude from config.file

### ISSUE THREAD

**Issue by tekert** [prometheus-community/windows_exporter#1233]
```yml
collectors:
  enabled: '[defaults],process'
collector:
  process:
    include: ''    # don't include anything for testing
    exclude: '.*'  # exclude everything for testing
```

The event viewer shows:  `No filters specified for process collector. This will generate a very large number of metrics!`

(config file is working btw, i just extracted the part that is not working)

Version: v0.22.0
