### ISSUE TITLE
Feature Request: Allow Textfile collector to collect file from multiple paths

### ISSUE THREAD

**Issue by LaurenceChau** [prometheus-community/windows_exporter#1236]
Currently textfile collector can only collect file from one directory. Can add a new feature to allow it to collect file from multiple directories thanks. 

suggestion for the config.yaml
```
collectors:
  enabled: textfile
collector:
  textfile:
    directories: 
    - C:\Program Files\windows_exporter\textfile_inputs
    - C:\Program Files\windows_exporter\textfile_inputs2
```

suggestion for the cli
```
--collector.textfile.directories 'C:\Program Files\windows_exporter\textfile_inputs,C:\Program Files\windows_exporter\textfile_inputs2'
```
