### ISSUE TITLE
was collected before with the same name and label values after remove IIS Site

### ISSUE THREAD

**Issue by Yaume2** [prometheus-community/windows_exporter#1242]
I've got an exporter running since 1 year.
Today I remove an IIS Site : site1. 
Now explorer is broken : was collected before with the same name and label values for 37 metrics of Site2 (Site2 not Site1).
Exporter is installed from chocolatey.
I try to stop and start service and re-install exporter. No change.
I use this config file :

```yaml
collectors:
  enabled: cpu,cs,os,logical_disk,net,process,service,iis
collector:
  service:
    services-where: Name='W3SVC'
log:
  level: debug
scrape:
  timeout-margin: 0.5
telemetry:
  addr: ":9182"
  path: /metrics
  max-requests: 5
```

I can't restart IIS (need planification ans communication to do this).
Someone have an idea ?
