### ISSUE TITLE
Filter metrics based on hostname

### ISSUE THREAD

**Issue by mani9223-oss** [prometheus-community/windows_exporter#1296]
I want to filter metrics based on hostname. Right now metrics from multiple instances are showing as a combined value. We have a CF to create instances and install agents. So we have to separate metrics based on instance name

**Comment by JDA88** [comment]
Prometheus is supposed to add the instance label that should be the hostname

**Comment by mani9223-oss** [comment]
We have multiple EC2 instances for an environment, so here the instance label is the same for all instances in an environment which makes it difficult to separate metrics for different instances. Whereas for `windows_cs_hostname `query, I am getting a separate label hostname and that is what I need for all queries.

**Comment by JDA88** [comment]
I am not sure I understand exactly what you are doing. You have 2 instances with the same "instance" name but different hostnames?
Can you give me more details? (A simple version, with target details)

**Comment by mani9223-oss** [comment]
We have a single Prometheus server running remotely and we have this windows-exporter agent installed in multiple instances. These instances have a common endpoint (Let's say **_env1.company.com:9182_**) for emitting metrics. So the scrap job from Prometheus looks like this 
```
static_configs:
- job_name: windows-exporter-env1
  - targets:
    - env1.company.com:9182 (here 2 instances)
- job_name: windows-exporter-env2
  - targets:
    - env2.company.com:9182 (here 6 instances)
```

So the issue here is since all instances are reporting under a single DNS name and Prometheus server, the instance name looks the same for all instances(env1.company.com) and here the metrics cannot be separated based on hostname where the hostname label is available only for windows_cs_hostname query.
