### ISSUE TITLE
'--config.file' is not recognized as an internal or external command on 0.24.0 and 0.25.1

### ISSUE THREAD

**Issue by sesoldi** [prometheus-community/windows_exporter#1391]
I've built 2 images based on 0.24.0, and also tried with 0.25.1 with the same result.
I'm attempting to run this on AKS 1.28, on a windows node, but the pod fails to start.

This is our dockerfile, where we're also installing powershell and a few KBs in order to remediate vulnerabilities.

```
FROM ghcr.io/prometheus-community/windows-exporter:0.24.0
FROM mcr.microsoft.com/powershell

USER ContainerAdministrator

RUN powershell -Command \
    "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12;" \
    "Install-PackageProvider -Name NuGet -Force;" \
    "Install-Module -Confirm:$false -Force -Name PSWindowsUpdate"

RUN powershell -Command \
    "Get-WindowsUpdate -Install -KBArticleID KB5031364 -AcceptAll -IgnoreUserInput;" \
    "Get-WindowsUpdate -Install -KBArticleID KB5032198 -AcceptAll -IgnoreUserInput;" \
    "Get-WindowsUpdate -Install -KBArticleID KB5033118 -AcceptAll -IgnoreUserInput"
USER ContainerUser
```

These are our DS and CM manifests.

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: win-prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: prometheus-windows-exporter
    app.kubernetes.io/part-of: prometheus-windows-exporter
    app.kubernetes.io/version: 0.24.0
    helm.sh/chart: prometheus-windows-exporter-0.2.0
  name: win-prometheus
  namespace: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: win-prometheus
      app.kubernetes.io/name: prometheus-windows-exporter
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      labels:
        app.kubernetes.io/component: metrics
        app.kubernetes.io/instance: win-prometheus
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: prometheus-windows-exporter
        app.kubernetes.io/part-of: prometheus-windows-exporter
        app.kubernetes.io/version: 0.24.0
        helm.sh/chart: prometheus-windows-exporter-0.2.0
    spec:
      automountServiceAccountToken: false
      containers:
      - args:
        - --config.file=%CONTAINER_SANDBOX_MOUNT_POINT%/config.yml
        - --collector.textfile.directories=%CONTAINER_SANDBOX_MOUNT_POINT%
        - --web.listen-address=:9182
        env: null
        image: xxxxx/xxxx-win-prometheus-node-exporter:1.28.latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            httpHeaders: null
            path: /
            port: 9182
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: windows-exporter
        ports:
        - containerPort: 9182
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            httpHeaders: null
            path: /
            port: 9182
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /config.yml
          name: config
          subPath: config.yml
      hostNetwork: true
      hostPID: true
      imagePullSecrets:
      - name: xxxx-docker-registry-secret
      initContainers:
      - args:
        - New-NetFirewallRule
        - -DisplayName
        - '''windows-exporter'''
        - -Direction
        - inbound
        - -Profile
        - Any
        - -Action
        - Allow
        - -LocalPort
        - "9182"
        - -Protocol
        - TCP
        command:
        - powershell
        image: xxxxx/xxxxxx-win-prometheus-node-exporter:1.28.latest
        name: configure-firewall
      nodeSelector:
        kubernetes.io/os: windows
      securityContext:
        windowsOptions:
          hostProcess: true
          runAsUserName: NT AUTHORITY\system
      serviceAccountName: win-prometheus
      tolerations:
      - effect: NoSchedule
        operator: Exists
      volumes:
      - configMap:
          name: win-prometheus
        name: config
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
---
apiVersion: v1
data:
  config.yml: |
    collectors:
      enabled: '[defaults],container'
    collector:
      service:
        services-where: "Name='containerd' or Name='kubelet'"
    telemetry:
      addr: ":9182"
      path: /metrics
      max-requests: 5
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: win-prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: prometheus-windows-exporter
    app.kubernetes.io/part-of: prometheus-windows-exporter
    app.kubernetes.io/version: 0.24.0
    helm.sh/chart: prometheus-windows-exporter-0.2.0
  name: win-prometheus
  namespace: prometheus
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: win-prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: prometheus-windows-exporter
    app.kubernetes.io/part-of: prometheus-windows-exporter
    app.kubernetes.io/version: 0.24.0
    helm.sh/chart: prometheus-windows-exporter-0.2.0
  name: win-prometheus
  namespace: prometheus
---
```

The pod spins up and immediately goes into CrashLoopBackOff.
Describing the pod initially it indicates that it's not able to reach the probes.

```
Warning  Unhealthy  13m (x8 over 14m)     kubelet            Readiness probe failed: Get "http://10.0.0.10:9182/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy  13m (x2 over 14m)     kubelet            Liveness probe failed: Get "http://10.0.0.10:9182/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

However, looking into the logs of the container it appears that it's not finding the process.

```
C:\Users\xxxxx\.kube\Projects YAML\prometheus>kubectl -n prometheus logs win-prometheus
Defaulted container "windows-exporter" out of: windows-exporter, configure-firewall (init)
'--config.file' is not recognized as an internal or external command,
operable program or batch file.
```

I went over the documentation, and the DS template in the chart, and it appears that configuration is identical as suggested:

```
      containers:
        - name: windows-exporter
          image: {{ include "prometheus-windows-exporter.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --config.file=%CONTAINER_SANDBOX_MOUNT_POINT%/config.yml
            - --collector.textfile.directory=%CONTAINER_SANDBOX_MOUNT_POINT%
            - --web.listen-address=:{{ .Values.service.port }}
            {{- with .Values.extraArgs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.containerSecurityContext }}
```
