### ISSUE TITLE
Error: Error reading directory: C:\\hpc\\textfile_inputs

### ISSUE THREAD

**Issue by nietjoost** [prometheus-community/windows_exporter#1514]
Hi all, after deploying the windows_exporter the container gives the error every 30 seconds:

caller=textfile.go:299 level=error collector=textfile msg="Error reading directory: C:\\hpc\\textfile_inputs" err="CreateFile C:\\hpc\\textfile_inputs: The system cannot find the file specified."

Creating the folder manually on the node does resolve the error messages in the container. But that is not really a solution. Does anyone know what the issue could be? 

Thanks in advance!

**Comment by jkroepke** [comment]
Define

> --collector.textfile.directories=""

May help.

By default, the textfile collector is on an the flag has a default value

**Comment by jkroepke** [comment]
@breed808 What did you think about disable the textfile collector by default. I guess the rarely used and confused a lot of people.

Alternatively, remove the default path and leave them empty. That how [node_exporter](https://github.com/prometheus/node_exporter/blob/dae4c87f7d54803340ccc065bee6cb6dd400af99/collector/textfile.go#L36) does this.

**Comment by nietjoost** [comment]
@jkroepke  Thank you for your answer. I tested your solution, but this does not disable the feature "collector.textfile.directories". It now searches for an folder without a name.

**Comment by jkroepke** [comment]
> It now searches for an folder without a name.

I would still leave this issue open.

**Comment by gosharplite** [comment]
Base on [codes](https://github.com/prometheus-community/windows_exporter/blob/master/exporter.go#L101-L104),
```
		enabledCollectors = app.Flag(
			"collectors.enabled",
			"Comma-separated list of collectors to use. Use '[defaults]' as a placeholder for all the collectors enabled by default.").
			Default(types.DefaultCollectors).String()
```

below configmap will exclude the textfile feature.
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: windows-exporter-config
  namespace: windows-monitoring
  labels:
    app: windows-exporter
data:
  config.yml: |
    collectors:
      enabled: 'cpu,cs,logical_disk,physical_disk,net,os,service,system,container'
    collector:
      service:
        services-where: "Name='containerd' or Name='kubelet'"
```
