### ISSUE TITLE
 Prometheus error: "context deadline exceeded"

### ISSUE THREAD

**Issue by grannymaster** [prometheus-community/windows_exporter#1534]
Hey, 

I'm having some trouble with the exporter and Prometheus.

I've installed it using "windows_exporter-0.26.0-amd64" without changing any settings, as I only want basic CPU, GPU, and RAM monitoring.

Prometheus is giving me this error:
	`Get "http://192.168.50.2:9182/metrics": context deadline exceeded`

This is my Prometheus job config:

```
  - job_name: gaming_PC
    scrape_interval: 5m
    scrape_timeout: 1m
    static_configs:
      - targets:
        - 192.168.50.2:9182
```
		
I first tried without defining scrape_interval and scrape_timeout, and then changed them to bigger numbers. No effect there.

If I go to `http://192.168.50.2:9182/metrics` I can see the metrics and values.

Did I mess something up?
