### ISSUE TITLE
windows_exporter produces high CPU load

### ISSUE THREAD

**Issue by thomasjoscht** [prometheus-community/windows_exporter#1726]
### Problem Statement

Hey, we've encoutered a very high cpu load produced by windows_exporter.exe. It is installed on every windows server 2019/2022 and Hyper-V VM in our environment. On our physical server the cpu load is < 1 %, but on our VM's it's incredible high between 5 % and 20 % of CPU all the time (showing in Task Manager).

That is our config.yml:
```
collectors:
  enabled: cpu,cs,logical_disk,net,os,service,system,textfile,logon
log:
  level: warn
scrape:
  timeout-margin: 0.5
telemetry:
  addr: ":9182"
  path: /metrics
  max-requests: 5
```

Is it possible to reduce the consuming cpu load of the process? I haven't found any configuration parameter for scaning interval. The only thing what could work is to reduce used collectors. But I thought default collectors are not as challenging. Perhaps I'm missing something here?

Thx a lot.

### Environment

- windows_exporter Version: 0.25.1
- Windows Server Version: 2019/2022
