### ISSUE TITLE
Metrics for "AppV Client Streamed Data Percentage" and "User Input Delay per Process/Session" and "Bitlocker" - Windows PDH

### ISSUE THREAD

**Issue by Nachtfalkeaw** [prometheus-community/windows_exporter#1781]
### Problem Statement

Hello,

on this website I found - if I am not wrong - some metricd which maybe can be collected using PDH.
https://gist.github.com/shadowbq/7babb99078721c153346fed4173059ad

AppV:
I am personally interested in "AppV" because our company streams most of the Apps for Endusers using "AppV". Maybe I can get better understanding why Apps load slow (at first time ) or are slow with these counters.

"User Input Delay per Session" and "User Input Delay per Process"
In addition many of our servers are running on "VMware" or Citrix Netscaler Sessions. The user experience is sometimes very bad and maybe these counters can help me to identify if it is related to an input delay.

"Bitlocker"
My company plans to encrypt devices using BitLocker and having some metrics related to this may help.,

---

"Power Meter" and "Energy Meter"
This is more "fun" or at least because at our company we always here "green IT" and we should save energy. Could be fun to have some values how much "energy" the endusers computers/notebooks need.

---

Something I did not found a solution for is "per process network" metrics like I have these in the Task Manager. There only exists metrics counting read/write on the filesystem + network traffic but never network traffic on its own per process. Not sure if PDH offer a solution for that.

### Proposed Solution

Add metrics for:

AppV
Bitlocker
User Input Delay Session and process
Energy Meter
Power Meter
Network Metrics per process

### Additional information

Source:
https://gist.github.com/shadowbq/7babb99078721c153346fed4173059ad

**Comment by jkroepke** [comment]
Hi,

there is a relative new collector in the upcoming release that allowed end-users to define any kind for performance counters and export them as metric.

https://github.com/prometheus-community/windows_exporter/blob/master/docs/collector.performancecounter.md

I guess, this feature request can be handled by that collector.

**Comment by Nachtfalkeaw** [comment]
Do you have a link to these PDH ? Any maybe a more accurate match between the yml/json file and the values you took from microsoft/PDH.

I have difficulties to understand what is "free text" and what needs to match.

maybe you can help me and gibe me the link to these:

- object: "Processor Information"
- object: "Memory"

and I may try to map it myself.

**Comment by Nachtfalkeaw** [comment]
Hello,
i tried to implement the example from the docs but it does not collect any metrics:
I tried with json and yml format. no results.


```
collectors:
  enabled: memory,performancecounter

collector:
  performancecounter:
    objects:
      [
        {
          "object": "Memory",
          "counters": [
            {
              "name": "Cache Faults/sec",
              "type": "counter"
            }
          ]
        }
      ]

##      - object: "Memory"
##        counters:
##          - name: "Cache Faults/sec"
##            type: "counter" # optional

log:
  level: debug
scrape:
  timeout-margin: 0.5
telemetry:
  path: /metrics
  max-requests: 0
web:
  listen-address: ":9182"

```


This is the command I use to start it:
`C:\Users\Alexander\Desktop\windows_exporter-0.30.0-rc.2-amd64.exe --config.file="C:\Users\Alexander\Desktop\windows_exporter.yml" --log.file="C:\Users\Alexander\Desktop\windows_exporter.log"`


And this is the debug log after starting and scraping the /metrics endpoint:
```
time=2024-12-05T11:17:22.222+01:00 level=INFO source=config.go:79 msg="Loading configuration file: C:\\Users\\Alexander\\Desktop\\windows_exporter.yml"
time=2024-12-05T11:17:22.276+01:00 level=DEBUG source=main.go:188 msg="Logging has Started"
time=2024-12-05T11:17:22.276+01:00 level=DEBUG source=main.go:327 msg="setting process priority to normal"
time=2024-12-05T11:17:22.281+01:00 level=INFO source=main.go:301 msg="Running as NACHTFALKE\\Alexander"
time=2024-12-05T11:17:22.281+01:00 level=INFO source=main.go:218 msg="Enabled collectors: performancecounter"
time=2024-12-05T11:17:22.281+01:00 level=INFO source=main.go:236 msg="starting windows_exporter in 60.5671ms" version=0.30.0-rc.2 branch=HEAD revision=f5ff75ebc26c5b4dd3f1d07701e6fca9fd944fe3 goversion=go1.23.3 builddate=20241130-12:12:25 maxprocs=12
time=2024-12-05T11:17:22.281+01:00 level=INFO source=tls_config.go:347 msg="Listening on" address=[::]:9182
time=2024-12-05T11:17:22.281+01:00 level=INFO source=tls_config.go:350 msg="TLS is disabled." http2=false address=[::]:9182
time=2024-12-05T11:17:28.271+01:00 level=DEBUG source=collect.go:220 msg="collector performancecounter succeeded after 0s, resulting in 0 metrics"
```

**Comment by jkroepke** [comment]
The issue is related to the config yaml. Good hint here.

Since YAML also parse JSON as YAML, the just must be marked as string.

```yaml
collector:
  performancecounter:
    objects: |
      [
        {
          "object": "Memory",
          "counters": [
            {
              "name": "Cache Faults/sec",
              "type": "counter"
            }
          ]
        }
      ]
```

Take note of the pipe

**Comment by Nachtfalkeaw** [comment]
your last snipped worked, however I had issues to add a second object. For me the YAML is easier to read. Unfortunately this YAML snippet does not work in the config file.

```
collector:
  performancecounter:
    objects:
      - object: "Memory"
        counters:
          - name: "Cache Faults/sec"
            type: "counter"
```

**Comment by jkroepke** [comment]
> Unfortunately this YAML snippet does not work in the config file.

Again, you have to add a pipe there:


``` yaml
collector:
  performancecounter:
    objects: |
      - object: "Memory"
        counters:
          - name: "Cache Faults/sec"
            type: "counter"
```

> PS:

I'm happy for any improvements from end-user perspective. 

Thanks!

**Comment by Nachtfalkeaw** [comment]
Without the pipe in yaml format it at least starts the windows_exporter.
with the pipe I get this error:

```
collector:
  performancecounter:
### not working YAML
    objects: |
      - object: "Memory"
        counters:
          - name: "Cache Faults/sec"
            type: "counter"
      
      - object: "BitLocker"
        instances:
          - "C:"
          - "E:"
          - "F:"
        instance_label: "Laufwerk"
        counters:
          - name: "Write Requests/sec"
            type: "counter"
      
      - object: "BitLocker"
        instances:
          - "D:"
          - "G:"
          - "H:"
        instance_label: "DLaufwerk"
        counters:
          - name: "Read Requests/sec"
            type: "counter"

```

Error:

```
time=2024-12-06T00:53:29.919+01:00 level=INFO source=config.go:79 msg="Loading configuration file: C:\\Users\\Alexander\\Desktop\\windows_exporter.yml"
time=2024-12-06T00:53:29.960+01:00 level=ERROR source=main.go:170 msg="Failed to parse CLI args from YAML file" err="failed to parse objects: invalid character ' ' in numeric literal"
```

the rest of my config file is this but it worked before:
```
log:
  level: debug
scrape:
  timeout-margin: 0.5
telemetry:
  path: /metrics
  max-requests: 0
web:
  listen-address: ":9182"
  disable-exporter-metrics: true     ## disabled go, prom metrics
```
