### ISSUE TITLE
0.25.1 upgrade to 0.29.2 can not get metrics in prometheus

### ISSUE THREAD

**Issue by qq952445491** [prometheus-community/windows_exporter#1813]
### Problem Statement

windows_exporter log:
ts=2024-12-11T16:46:19.230+08:00 level=warn caller=prometheus.go:256 msg="collector process timeouted after 0s, resulting in 0 metrics"
ts=2024-12-11T16:46:19.230+08:00 level=warn caller=prometheus.go:256 msg="collector memory timeouted after 0s, resulting in 0 metrics"
ts=2024-12-11T16:46:19.230+08:00 level=warn caller=prometheus.go:256 msg="collector cpu timeouted after 0s, resulting in 0 metrics"
ts=2024-12-11T16:46:19.230+08:00 level=warn caller=prometheus.go:256 msg="collector os timeouted after 0s, resulting in 0 metrics"
ts=2024-12-11T16:46:19.230+08:00 level=warn caller=prometheus.go:256 msg="collector logical_disk timeouted after 0s, resulting in 0 metrics"
ts=2024-12-11T16:46:19.230+08:00 level=warn caller=prometheus.go:256 msg="collector cs timeouted after 0s, resulting in 0 metrics"
ts=2024-12-11T16:46:19.230+08:00 level=warn caller=prometheus.go:256 msg="collector service timeouted after 0s, resulting in 0 metrics"
ts=2024-12-11T16:46:19.230+08:00 level=warn caller=prometheus.go:256 msg="collector system timeouted after 0s, resulting in 0 metrics"
ts=2024-12-11T16:46:20.201+08:00 level=warn caller=prometheus.go:256 msg="collector os timeouted after 0s, resulting in 0 metrics"

and config.yml:
collectors:
  enabled: cpu,cs,logical_disk,os,system,service,process,memory

collector:
  service:
    services-where: Name='W32Time'

### Environment

- windows_exporter Version: 0.29.2
- Windows Server Version: windows 11
- prometheus version: 2.42.0

**Comment by Kherm13** [comment]
Your `service-where` should be `include` for starters. The `services-where` was deprecated. https://github.com/prometheus-community/windows_exporter/pull/1634

So it should look like...

```
collector:
  service:
     include: 'W32Time'
```

**Comment by qq952445491** [comment]
> Your `service-where` should be `include` for starters. The `services-where` was deprecated. #1634
> 
> So it should look like...
> 
> ```
> collector:
>   service:
>      include: 'W32Time'
> ```

Thanks for your reply， but it can not resolve this problem, and log is also print that "collector os timeouted after 0s, resulting in 0 metrics"

and config.yml:

collectors:
  enabled: cpu,cs,logical_disk,os,system,service,process,memory

collector:
  service:
    include: 'W32Time'

**Comment by jkroepke** [comment]
Do you open the metrics endpoint by hand or via Prometheus? If Prometheus, post your scrape config.

**Comment by qq952445491** [comment]
> Do you open the metrics endpoint by hand or via Prometheus? If Prometheus, post your scrape config.

prometheus.yml:

# my global config
global:
  scrape_interval: 1s # Set the scrape interval to every 1 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 5 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "localhost:9093"

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "rules/*_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9091"]

  - job_name: "server"
    static_configs:
      - targets: ["localhost:9182"]

**Comment by qq952445491** [comment]
> Do you open the metrics endpoint by hand or via Prometheus? If Prometheus, post your scrape config.
prometheus.yml:

```
global:
  scrape_interval: 1s # Set the scrape interval to every 1 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 5 seconds. The default is every 1 minute.

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "localhost:9093"

rule_files:
  - "rules/*_rules.yml"

scrape_configs:
  - job_name: "prometheus"
``
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9091"]

  - job_name: "server"
    static_configs:
      - targets: ["localhost:9182"]

```
