### ISSUE TITLE
Performance counter name with specific chars cause application quit

### ISSUE THREAD

**Issue by kyue1005** [prometheus-community/windows_exporter#1828]
### Current Behavior

I found two situations causing the exporter fails when the counter contains specific characters:

1. colon `:`
```
collector:
  performancecounter:
    objects: |-
      - name: photon_udp
        object: "Photon Socket Server: UDP"
        instances: ["*"]
        counters:
          - name: "UDP: Datagrams in"
            metric: "photon_udp_datagrams"
            labels:
              direction: "in"
          - name: "UDP: Datagrams out"
            metric: "photon_udp_datagrams"
            labels:
              direction: "out"
 ```
 
2. brackets
 ```
collector:
  performancecounter:
    objects: |-
      - name: photon_enet
        object: "Photon Socket Server: ENet"
        instances: ["*"]
        counters:
          - name: "Acknowledgements in"
            metric: "photon_enet_acknowledgements"
            labels:
              direction: "in"
          - name: "Acknowledgements out"
            metric: "photon_enet_acknowledgements"
            labels:
              direction: "out"
          - name: "Client Timeout disconnects"
            metric: "photon_enet_client_timeout_disconnects"
          - name: "Connect Timeouts"
            metric: "photon_enet_connect_timeouts"
          - name: "Commands in/sec"
            metric: "photon_enet_commands_per_sec"
            labels:
              direction: "in"
          - name: "Commands out/sec"
            metric: "photon_enet_commands_per_sec"
            labels:
              direction: "out"
          - name: "Datagram validation failures/sec"
            metric: "photon_enet_datagram_validation_failures_per_sec"
          - name: "Flow control (oversize) buffers in use"
            metric: "photon_enet_flow_control_oversize_buffers_in_use"
          - name: "Pings in"
            metric: "photon_enet_pings"
            labels:
              direction: "in"
          - name: "Pings out"
            metric: "photon_enet_pings"
            labels:
              direction: "out"
          - name: "Reliable commands (in) dropped (Q)/sec"
              metric: "photon_enet_reliable_commands_dropped_per_sec"
            labels:
              direction: "in"
              reason: "queuesfull"
          - name: "Reliable commands (in) dropped (Dup)/sec"
            metric: "photon_enet_reliable_commands_dropped_per_sec"
            labels:
              direction: "in"
              reason: "duplicate"
          - name: "Reliable commands (in) dropped (Seq)/sec"
            metric: "photon_enet_reliable_commands_dropped_per_sec"
            labels:
              direction: "in"
              reason: "sequence"
 ```

the application just quit after displaying the warning message

### Expected Behavior

those characters in counter name should not break the application

### Environment

- windows_exporter Version: 0.30.0-rc.4
- Windows Server Version: Windows Pro 11

### windows_exporter logs

```shell
time=2025-01-10T14:50:50.533Z level=INFO source=config.go:79 msg="loading configuration file: local/config.yaml"
time=2025-01-10T14:50:50.533Z level=DEBUG source=main.go:196 msg="logging has Started"
time=2025-01-10T14:50:50.533Z level=DEBUG source=main.go:337 msg="setting process priority to normal"
time=2025-01-10T14:50:50.535Z level=WARN source=os.go:108 msg="The os collect holds a number of deprecated metrics and will be removed mid 2025. See https://github.com/prometheus-community/windows_exporter/pull/1596 for more information." collector=os
panic: reflect.StructOf: field 7 has invalid name

goroutine 37 [running]:
reflect.StructOf({0xc0003b8808, 0x13, 0xc00004bf18?})
        C:/hostedtoolcache/windows/go/1.23.4/x64/src/reflect/type.go:2371 +0x2694
github.com/prometheus-community/windows_exporter/internal/collector/performancecounter.(*Collector).Build(0xc000370640, 0xc000407c20, 0xf49440?)
        D:/a/windows_exporter/windows_exporter/internal/collector/performancecounter/performancecounter.go:193 +0x1525
github.com/prometheus-community/windows_exporter/pkg/collector.(*Collection).Build.func1()
        D:/a/windows_exporter/windows_exporter/pkg/collector/collection.go:220 +0x8a
created by github.com/prometheus-community/windows_exporter/pkg/collector.(*Collection).Build in goroutine 1
        D:/a/windows_exporter/windows_exporter/pkg/collector/collection.go:217 +0x1e5
```
