### ISSUE TITLE
How to configure netframework collector after merge?

### ISSUE THREAD

**Issue by JohannesEH** [prometheus-community/windows_exporter#1832]
### Problem Statement

I can't for the life of me figure out how to enable the individual netframework collectors after the netframerwork_x collector merge in 0.29.0. I'm using a yaml file and I've tried a variety of formats. How is it supposed to look?

```yaml
collectors:
  enabled: '[defaults],netframework'
collector:
  netframework:
    collectors:
      enabled:
      - clrloading
      - clrlocksandthreads
      - clrmemorycollector
```

### Environment

- windows_exporter Version: 0.29.2
- Windows Server Version: 2019
