### ISSUE TITLE
netframework collector queries fail afer upgrading to 0.30.1 (that switched to Windows Management Infrastructure)

### ISSUE THREAD

**Issue by lucasfsvilela** [prometheus-community/windows_exporter#1856]
### Current Behavior

Windows Exporter (0.30.1) is configured with some netframework collectors:

```
    collectors:
      enabled: "container,cpu,cpu_info,cs,logical_disk,memory,net,netframework,os,process,service,system"
    collector:
      netframework:
        enabled: "clrexceptions,clrlocksandthreads,clrmemory"
```

But no netframework collectors metrics are being collected. At log, I can see error with WMI query:

`time=2025-01-24T14:39:12.309Z level=WARN source=collect.go:212 msg="collector netframework failed after 36.2285ms, resulting in 0 metrics" err="WMI query failed: WMI query failed: MI_RESULT_INVALID_QUERY: \nWMI query failed: WMI query failed: MI_RESULT_INVALID_QUERY: \nWMI query failed: WMI query failed: MI_RESULT_INVALID_QUERY: "`

These metrics were being collected fine when running older version 0.24.0

### Expected Behavior

Metrics from netframework collectors should be collected as usual.

### Steps To Reproduce

```Markdown

```

### Environment

- windows_exporter Version: 0.30.1
- Windows Server Version: Windows Server 2022 Datacenter

### windows_exporter logs

```shell
time=2025-01-24T14:49:12.300Z level=WARN source=collect.go:212 msg="collector netframework failed after 23.3139ms, resulting in 0 metrics" err="WMI query failed: WMI query failed: MI_RESULT_INVALID_QUERY: \nWMI query failed: WMI query failed: MI_RESULT_INVALID_QUERY: \nWMI query failed: WMI query failed: MI_RESULT_INVALID_QUERY: "
```
