### ISSUE TITLE
How to collect network metrics based on process

### ISSUE THREAD

**Issue by c4mmartin** [prometheus-community/windows_exporter#1916]
### Problem Statement

Sorry if i missed this but i am not seeing it in the documentation. is there a way to see network usage based on process or source/destination port? For example, running a windows application and i would like to see if the app runs into loops of running the same network endpoints over and over. 

### Environment

- windows_exporter Version:0.30.4
- Windows Server Version:Win11Pro 24H2

**Comment by c4mmartin** [comment]
Actually i think i may have figured something out for this using performancecounter, 

```yaml
objects:
  - name: "process_bandwidth"
    object: "Process"
    counters:
      - name: "IO Read Bytes/sec"
        metric: "process_io_read_bytes_per_sec"
        type: "gauge"
      - name: "IO Write Bytes/sec"
        metric: "process_io_write_bytes_per_sec"
        type: "gauge"
    instances: ["*"]
    instance_label: "process"
  - name: "network_activity"
    object: "Network Interface"
    counters:
      - name: "Bytes Received/sec"
        metric: "network_bytes_received_per_sec"
        type: "gauge"
      - name: "Bytes Sent/sec"
        metric: "network_bytes_sent_per_sec"
        type: "gauge"
    instances: ["*"]
    instance_label: "interface"
```
Thoughts?
