### ISSUE TITLE
The windows_exporter service terminated unexpectedly.

### ISSUE THREAD

**Issue by PugachevDK** [prometheus-community/windows_exporter#1959]
### Current Behavior

The windows_exporter service terminated unexpectedly.  It has done this 1 time(s).

### Expected Behavior

I use version 0.30.5
Config:
```yaml
---
collectors:
  enabled: cpu,logical_disk,memory,net,os,service,system,license,scheduled_task,textfile,time
collector:
  service:
    include: ^(QORT.*|windows\_exporter|winrm)$
    exclude: 
  scheduled_task:
    include: ^/BackQORT/.+
    exclude: 
  textfile:
    directories: c:\windows_exporter\textfile
log:
  level: info
  file: eventlog
  format: json
scrape:
  timeout-margin: 0.5
telemetry:
  path: /metrics
  max-requests: 0
web:
  listen-address: ":9182"
```
Service is crashing on some nodes. I attach logs file from the server, where there is something to look at in the log, except for startup events

Event in the System log:
```xml
Log Name:      System
Source:        Service Control Manager
Date:          31.03.2025 8:09:29
Event ID:      7034
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      kzp-bqort-02.corp.abylaigs.kz
Description:
The windows_exporter service terminated unexpectedly.  It has done this 1 time(s).
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Service Control Manager" Guid="{555908d1-a6d7-4695-8e1e-26931d2012f4}" EventSourceName="Service Control Manager" />
    <EventID Qualifiers="49152">7034</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8080000000000000</Keywords>
    <TimeCreated SystemTime="2025-03-31T05:09:29.2848407Z" />
    <EventRecordID>13858</EventRecordID>
    <Correlation />
    <Execution ProcessID="732" ThreadID="3008" />
    <Channel>System</Channel>
    <Computer>kzp-bqort-02.corp.abylaigs.kz</Computer>
    <Security />
  </System>
  <EventData>
    <Data Name="param1">windows_exporter</Data>
    <Data Name="param2">1</Data>
    <Binary>770069006E0064006F00770073005F006500780070006F0072007400650072000000</Binary>
  </EventData>
</Event>
```

### Steps To Reproduce

```Markdown

```

### Environment

- windows_exporter Version: 0.30.5
- Windows Server Version: Windows Server 2022 Datacenter

### windows_exporter logs

```shell
{"time":"2025-03-30T22:49:29.2790127Z","level":"WARN","source":"collect.go:212","msg":"collector memory failed after 4.519ms, resulting in 3 metrics","err":"panic in collector memory: runtime error: index out of range [0] with length 0. stack: goroutine 19412 [running]:\nruntime/debug.Stack()\n\tC:/Users/runneradmin/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.4.windows-amd64/src/runtime/debug/stack.go:26 +0x5e\ngithub.com/prometheus-community/windows_exporter/pkg/collector.(*Collection).collectCollector.func1.1()\n\tD:/a/windows_exporter/windows_exporter/pkg/collector/collect.go:128 +0x65\npanic({0x12758a0?, 0xc000198000?})\n\tC:/Users/runneradmin/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.4.windows-amd64/src/runtime/panic.go:785 +0x132\ngithub.com/prometheus-community/windows_exporter/internal/collector/memory.(*Collector).collectPDH(0xc0002b2000, 0xc0005b3650)\n\tD:/a/windows_exporter/windows_exporter/internal/collector/memory/memory.go:416 +0x1109\ngithub.com/prometheus-community/windows_exporter/internal/collector/memory.(*Collector).Collect(0xc0002b2000, 0xc0005b3650)\n\tD:/a/windows_exporter/windows_exporter/internal/collector/memory/memory.go:351 +0x45\ngithub.com/prometheus-community/windows_exporter/pkg/collector.(*Collection).collectCollector.func1()\n\tD:/a/windows_exporter/windows_exporter/pkg/collector/collect.go:135 +0x82\ncreated by github.com/prometheus-community/windows_exporter/pkg/collector.(*Collection).collectCollector in goroutine 19400\n\tD:/a/windows_exporter/windows_exporter/pkg/collector/collect.go:124 +0x1aa\n"}
```

### Anything else?

[windows_exporter_events.zip](https://github.com/user-attachments/files/19530244/windows_exporter_events.zip)
