### ISSUE TITLE
New Metrics with PerformanceCounter

### ISSUE THREAD

**Issue by GudmoNova** [prometheus-community/windows_exporter#1962]
### Problem Statement

I have a yaml config file like this on a windows server 2022 hyperv host
...
```
collectors:
  enabled: service,hyperv,mscluster,cache,cpu,cpu_info,logical_disk,memory,net,process,system,tcp,udp,diskdrive,physical_disk,performancecounter
  collector:
    mscluster:
        enabled: Network,Cluster,Code,ResourceGroup
  performancecounter:
    objects: |-
      - name: smbdirectconnection
        object: "SMD Direct Connection"
        instances: ["*"]
        counters:
          - name: "Bytes RDMA Read/sec"
          - name: "Bytes RDMA Written/sec"
          - name: "Bytes Received/sec"
          - name: "Bytes Sent/sec"
          - name: "Receives/sec"
          - name: "Sends/sec"

      - name: networkqospolicy
        object: "Network QoS Policy"
        instances: ["*"]
        counters:
          - name: "Bytes transmitted"
          - name: "Bytes transmitted/sec"
          - name: "Packets dropped"
          - name: "Packets dropped/sec"
          - name: "Packets transmitted"
          - name: "Packets transmitted/sec"

      - name: rdmaactivity
        object: "RDMA Activity"
        instances: ["*"]
        counters:
          - name: "RDMA Accepted Connections"
          - name: "RDMA Active Connections"
          - name: "RDMA Completion Queue Errors"
          - name: "RDMA Connection Errors"
          - name: "RDMA Failed Connection Attempts"
          - name: "RDMA Inbound Bytes/sec"
          - name: "RDMA Inbound Frames/sec"
          - name: "RDMA Initiated Connections"
          - name: "RDMA Outbound Bytes/sec"
          - name: "RDMA Outbound Frames/sec"
log:
  level: debug
```
...
I'm trying to limit the mscluster information and get some clearer metrics on my S2D setup.
But the new counters are completely ignored and the mscluster enabled won't work.
...
```
time=2025-03-31T15:55:04.729Z level=DEBUG source=collect.go:220 msg="collector performancecounter succeeded after 534.3µs, resulting in 0 metrics"
time=2025-03-31T15:55:04.736Z level=DEBUG source=collect.go:220 msg="collector memory succeeded after 8.3011ms, resulting in 35 metrics"
time=2025-03-31T15:55:04.737Z level=DEBUG source=collect.go:220 msg="collector cache succeeded after 8.9146ms, resulting in 29 metrics"
time=2025-03-31T15:55:04.737Z level=DEBUG source=collect.go:220 msg="collector physical_disk succeeded after 8.9146ms, resulting in 156 metrics"
time=2025-03-31T15:55:04.740Z level=DEBUG source=collect.go:220 msg="collector tcp succeeded after 12.3242ms, resulting in 22 metrics"
time=2025-03-31T15:55:04.741Z level=DEBUG source=collect.go:220 msg="collector cpu_info succeeded after 12.9621ms, resulting in 14 metrics"
time=2025-03-31T15:55:04.742Z level=DEBUG source=collect.go:220 msg="collector logical_disk succeeded after 13.7871ms, resulting in 51 metrics"
time=2025-03-31T15:55:04.744Z level=DEBUG source=collect.go:220 msg="collector net succeeded after 15.6283ms, resulting in 85 metrics"
time=2025-03-31T15:55:04.745Z level=DEBUG source=collect.go:220 msg="collector service succeeded after 17.5038ms, resulting in 2378 metrics"
time=2025-03-31T15:55:04.746Z level=DEBUG source=collect.go:220 msg="collector hyperv succeeded after 18.2346ms, resulting in 4270 metrics"
time=2025-03-31T15:55:04.747Z level=DEBUG source=collect.go:220 msg="collector cpu succeeded after 18.8468ms, resulting in 1825 metrics"
time=2025-03-31T15:55:04.748Z level=DEBUG source=collect.go:220 msg="collector system succeeded after 19.9034ms, resulting in 8 metrics"
time=2025-03-31T15:55:04.755Z level=DEBUG source=collect.go:220 msg="collector udp succeeded after 27.1938ms, resulting in 8 metrics"
time=2025-03-31T15:55:04.757Z level=DEBUG source=collect.go:220 msg="collector diskdrive succeeded after 28.823ms, resulting in 180 metrics"
time=2025-03-31T15:55:04.899Z level=DEBUG source=collect.go:220 msg="collector process succeeded after 170.2689ms, resulting in 3358 metrics"
time=2025-03-31T15:55:06.248Z level=DEBUG source=collect.go:220 msg="collector mscluster succeeded after 1.520234s, resulting in 13512 metrics"
```
...
mscluster still loading 13k objects and performancecounter 0.
I've tried to include only the mscluster_cluster... etc  but then the config won't load as it cannot find the subcounter objects like mscluster_cluster or mscluster_network.

Any help would be awesome!

### Environment

- windows_exporter Version: 0.30.5
- Windows Server Version: 2022

**Comment by jkroepke** [comment]
Please use code blocks next time

````markdown
```
TEST
```
````

I see that indention is wrong. This is correct

```yaml
collectors:
  enabled: service,hyperv,mscluster,cache,cpu,cpu_info,logical_disk,memory,net,process,system,tcp,udp,diskdrive,physical_disk,performancecounter
collector:
  mscluster:
    enabled: Network,Cluster,Code,ResourceGroup
  performancecounter:
```
