### ISSUE TITLE
No metrics being available in Prometheus even after metrics available at http://localhost:9182/metrics

### ISSUE THREAD

**Issue by simtcrom** [prometheus-community/windows_exporter#2001]
### Problem Statement

I am running v0.30.6 msi version of window_exporter.
service is started and http://localhost:9182/metrics page shows metrics being collected.

In Prometheus, config is setup as below,

```
scrape_configs:
  - job_name: "windows"
    scrape_interval: 30s
    static_configs:
      - targets: ["<ipofwindows>:9182"]
```

Issue is, no metrics being shown in prometheus.
For eg, http://localhost:9182/metrics shows windows_cpu_logical_processor as 4

![Image](https://github.com/user-attachments/assets/b0a05b74-417e-4020-b684-62994af53cd9)

But Prometheus not showing that,

![Image](https://github.com/user-attachments/assets/150201ae-242e-4a2a-bdc5-1c6dd771485d)

Debugging performed,

- Prometheus->Status->Traget Health shows the windows traget as up.
- From Prometheus server I could ```telnet <ipofwindows> 9182```  successfully.
- From Prometheus server I could ```curl http://<ipofwindows>:9182/metrics``` successfully.

On the windows events, I can see a lot warning as below,

```
source=collect.go:195 msg="collector memory timeouted after 0s, resulting in 0 metrics"
source=collect.go:195 msg="collector cs timeouted after 0s, resulting in 0 metrics"
source=collect.go:195 msg="collector cpu timeouted after 0s, resulting in 0 metrics"
```

Any idea how to solve my problem?

### Environment

- windows_exporter Version: v0.30.6
- Windows Server Version: Windows 10

**Comment by jkroepke** [comment]
It seems like your scrape timeout of 1 seconds is too low?

**Comment by simtcrom** [comment]
> It seems like your scrape timeout of 1 seconds is too low?
Thank you for the tip. That was the issue. I modified Prometheus config to have dedicated ```scrape_interval``` and ```scrape_timeout``` for windows job as below,

```
scrape_configs:
  - job_name: "windows"
    scrape_interval: 5s
    scrape_timeout: 2s
    static_configs:
      - targets: ["xx.xx.xx.xx:9115"]
```
My global ```scrape_interval``` is 1s (and that works perfectly fine for linux nodes) that must have been causing issue for windows exporter.
