### ISSUE TITLE
The `logical_disk.volume-exclude` is not working...

### ISSUE THREAD

**Issue by Hummdis** [prometheus-community/windows_exporter#2008]
### Current Behavior

I have several servers that have a dedicated PageFile drive, so I exclude them from monitoring.  This has worked in the `config.yaml` file for a while, but since v0.30.5 it's not worked.

```yaml
collectors:
  enabled: "[defaults],cpu_info,remote_fx,process,pagefile,mssql"
  collector:
    process:
      include: ['wuauserv', 'windows_exporter']
    # For MSSQL server metrics
    mssql:
      classes-enabled: accessmethods,bufman,databases,genstats,locks,memmgr,sqlstats,sqlerrors,transactions,waitstats
    textfile:
      directories: textfile_inputs
    logical_disk:
      volume-exclude: "(^S|Y):$"
```

As mentioned, this has worked.  This is not a new configuration.

The servers in question range from 2012 R2 Datacenter (qty. 1) to 2019 Datacenter.  All updated through at least March 2025.

While one server has two drives, most the others just have one and that line is something like:

```yaml
collectors:
  collector:
    logical_disk:
      volume-exclude: "E:"
```

### Expected Behavior

To ignore the specified volumes.

### Steps To Reproduce

```Markdown
Simply use v0.30.6 and specify ignoring a volume and it'll still show.
```

### Environment

- windows_exporter Version: 0.30.6
- Windows Server Version: 2012 R2 Datacenter to 2019 Datacenter

### windows_exporter logs

```shell
There are no errors or other issues reported.
```

### Anything else?

Here's an example metric from the server with both the `S:` and `Y:` drives told to ignore:

```text
# HELP windows_logical_disk_avg_write_requests_queued Average number of write requests that were queued for the selected disk during the sample interval (LogicalDisk.AvgDiskWriteQueueLength)
# TYPE windows_logical_disk_avg_write_requests_queued gauge
windows_logical_disk_avg_write_requests_queued{volume="C:"} 363713.7848944
windows_logical_disk_avg_write_requests_queued{volume="E:"} 71266.8805749
windows_logical_disk_avg_write_requests_queued{volume="F:"} 50.463904299999996
windows_logical_disk_avg_write_requests_queued{volume="HarddiskVolume1"} 169.4592121
windows_logical_disk_avg_write_requests_queued{volume="L:"} 92.08660859999999
windows_logical_disk_avg_write_requests_queued{volume="S:"} 165123.3229188
windows_logical_disk_avg_write_requests_queued{volume="X:"} 2.8009106999999998
windows_logical_disk_avg_write_requests_queued{volume="Y:"} 165094.2029606
windows_logical_disk_avg_write_requests_queued{volume="Z:"} 2.6181711
```

**Comment by jkroepke** [comment]
Your config might not correct at this point. this would be the correct one:

```yaml

collectors:
  enabled: "[defaults],cpu_info,remote_fx,process,pagefile,mssql"
collector:
  process:
    include: ['wuauserv', 'windows_exporter']
  # For MSSQL server metrics
  mssql:
    classes-enabled: accessmethods,bufman,databases,genstats,locks,memmgr,sqlstats,sqlerrors,transactions,waitstats
  textfile:
    directories: textfile_inputs
  logical_disk:
    volume-exclude: "(^S|Y):$"
```

The key `collector` where never below `collectors`
