### ISSUE TITLE
Container names or labels

### ISSUE THREAD

**Issue by usego** [prometheus-community/windows_exporter#357]
I have number of Windows servers running different type of containers. Any chance to get container names and/or labels to simplify identifying of containers? At this moment only container_id are in metrics, which is hard to consume in prometheus / graphana.

**Comment by carlpett** [comment]
Hi @usego,
It looks like this should be possible, it appears we have all these fields available: [ContainerProperties spec](https://godoc.org/github.com/microsoft/hcsshim/internal/schema1#ContainerProperties).
I currently don't have any system with Windows containers running, so I don't have a good way to test this, though. If you'd like to contribute a PR, we'd gladly review it!

**Comment by Drewster727** [comment]
Unfortunately, I'm not seeing anything useful in the ContainerProperties spec:
![image](https://user-images.githubusercontent.com/4528753/61586020-ea0c5480-ab2f-11e9-8944-98d67e99a76f.png)

**Comment by Drewster727** [comment]
@carlpett welp, per:
https://github.com/microsoft/hcsshim/issues/652

Looks like hcsshim won't provide what is needed. Is there another common library we can utilize to integrate?
-Drew

**Comment by carlpett** [comment]
Yep, we need to go about it differently for sure. I'm somewhat concerned about how to support this well, given that Windows aims to [support multiple "container platforms"](https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/containerd) (that is, not just Docker). CRI would probably be pretty similar to Docker support, but the more Hyper-V-like containers might not have the same concepts to map to.
Perhaps it would be easiest to get right if we do not put the labels on every metric, but rather have a `container_<type>_info` metric which can be used for lookups? Something like `wmi_container_docker_info{container_id="...", name="...", ...}`. This way we wouldn't run into issues if the different types don't have the same set of information. The queries will be a bit more complicated, of course, you'd need to do something like `wmi_container_cpu_usage_seconds_total * on(container_id) wmi_container_docker_info{name="my-container"}` etc.
What do you think?

**Comment by wyaopeng** [comment]
Can I use github.com/docker/docker/client to get container name then save to class instead microsoft/hcsshim Container_name?

**Comment by carlpett** [comment]
It is a fairly heavy package to import from a dependency point of view, so I'd rather not. How about generating the info metric I suggested above using a shell script and the `textfile` collector?

**Comment by Smuggla** [comment]
We ended up using Telegraf to get the Container Metrics from the Docker Daemon, maybe we can look at leveraging it the same way in this project? Can also map container_id with some regex...

https://github.com/influxdata/telegraf/blob/master/plugins/inputs/docker/docker.go

**Comment by AndrewFarley** [comment]
Hey folks, not to kick a dead horse here, but isn't this exporter useless without container names/labels?  Is there something I don't understand which can magically translate `container_id="containerd://032934897e303963da4402cc5510da0736f12ff6a56f1f77dd83845cd22d62be` objects into something meaningful for us to leverage these metrics?  Alertmanager, and Grafana are both useless without context of what this container actually is.

I understand maybe the problem is upstream if I'm reading some of the above correctly since hcsshim doesn't provide us this data.  What's the fix here?  We'd like to use Windows Containers in production, but basically without this issue resolved, as far as I can tell, metrics are (largely) useless and would require a lot of manual work to look up container IDs from running service, and from past services would be impossible.

To me, it seems like a simple fix when running this in a container via a Daemonset would be to allow this service an RBAC role which allows it to query the kubectl API and do a lookup to map the containerd IDs to pods details (namespace, name, etc).

**Comment by PatTheSilent** [comment]
@AndrewFarley the "barely making it useful" workaround I'm using is this set of promethes rules https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/rules/windows.libsonnet#L178 which adds some metrics with proper pod/container labels. 
I don't know how the standard node-exporter does this but the lack of these labels is really painful.

**Comment by godocean** [comment]
Hey folks, we're running standalone Windows Containers on top of Windows Servers without kubernetes, it's also useless for us to enable windows_exporter on the server to monitor windows containers without container name, how could we get the container name label from the metrics in that case? It seems that the only solution is to leverage github.com/docker/docker/client API, correct? 
But it was pointed out that the package is too heavy from above threads, right?

**Comment by AndrewFarley** [comment]
To me, the concept of a library being "heavy" is irrelevant if this package is useless without it

**Comment by AndrewFarley** [comment]
Following @PatTheSilent 's recommendation and work we were able to get something working and do so in a way that is backwards compatible and is based on the metrics which show up from [windows-exporter-daemonset.yaml](https://github.com/prometheus-community/windows_exporter/blob/master/kubernetes/windows-exporter-daemonset.yaml).  We are running AWS EKS 1.26 and have used the Helm Chart to run Prometheus.

Our Helm Chart values file for Prometheus itself (related to this topic) has the following...

```yaml

serverFiles:
  recording_rules.yml:
    groups:
      # This adds labels for the windows container name and pod name into our windows metrics which don't normally have it
      # Rules (loosely) below on https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/rules/windows.libsonnet#L178
      # Issue: https://github.com/prometheus-community/windows_exporter/issues/357
      - name: windows.pod.rules
        rules:
          # CPU USAGE MAP OVER EXISTING LINUX METRIC NAMES SO EXISTING DASHBOARDS WORKS
          - record: container_cpu_usage_seconds_total
            expr: windows_container_cpu_usage_seconds_total{service="windows-exporter", container_id != ""} * on(container_id) group_left(container, pod, namespace, image) max(kube_pod_container_info{job="kubernetes-pods", container_id != ""}) by(container, container_id, pod, namespace, image)
          # MEMORY USAGE MAP OVER EXISTING LINUX METRIC NAMES
          - record: container_memory_working_set_bytes
            expr: windows_container_memory_usage_commit_bytes{service="windows-exporter", container_id != ""} * on(container_id) group_left(container, pod, namespace, image) max(kube_pod_container_info{job="kubernetes-pods", container_id != ""}) by(container, container_id, pod, namespace, image)
          # NETWORK BANDWIDTH USAGE MAP OVER EXISTING LINUX METRIC NAMES
          # ---> RECEIVE...
          - record: container_network_receive_bytes_total
            expr: windows_container_network_receive_bytes_total{service="windows-exporter", container_id != ""} * on(container_id) group_left(container, pod, namespace, image) max(kube_pod_container_info{job="kubernetes-pods", container_id != ""}) by(container, container_id, pod, namespace, image)
          # ---> TRANSMIT/SEND...
          - record: container_network_transmit_bytes_total
            expr: windows_container_network_transmit_bytes_total{service="windows-exporter", container_id != ""} * on(container_id) group_left(container, pod, namespace, image) max(kube_pod_container_info{job="kubernetes-pods", container_id != ""}) by(container, container_id, pod, namespace, image)

          # Unused-ish?  But here anyways just incase...
          - record: windows_container_available_with_labels
            expr: windows_container_available{service="windows-exporter", container_id != ""} * on(container_id) group_left(container, pod, namespace, image) max(kube_pod_container_info{job="kubernetes-pods", container_id != ""}) by(container, container_id, pod, namespace, image)
          - record: windows_container_memory_usage_private_working_set_bytes_with_labels
            expr: windows_container_memory_usage_private_working_set_bytes{service="windows-exporter", container_id != ""} * on(container_id) group_left(container, pod, namespace, image) max(kube_pod_container_info{job="kubernetes-pods", container_id != ""}) by(container, container_id, pod, namespace, image)


```

And here's proof/example of it working with the Deployment/Daemonset/Statefulset dashboard, this is a screenshot of a service which runs entirely on Windows, and this dashboard works along-side any services which are Linux-based transparently.  I hope this helps save someone else the hours/days I've spent on making this work!

<img width="1335" alt="Screen Shot 2023-09-25 at 3 14 17 PM" src="https://github.com/prometheus-community/windows_exporter/assets/470163/693cff56-08cd-4c6d-aa74-f39b79ac80ff">
