### ISSUE TITLE
Rename to windows_exporter, move to prometheus-community

### ISSUE THREAD

**Issue by carlpett** [prometheus-community/windows_exporter#519]
As decided in #499, we will rename the exporter to windows_exporter. This issue tracks the required changes.
After these steps are completed, we will be ready to [move the repo](https://github.com/prometheus-community/community/issues/13) to the prometheus-community organization :tada:

- [x] Change metric namespace ([collector.go](https://github.com/martinlindhe/wmi_exporter/blob/54d94c261b37836cfc7d5e599f7f14a865b3e7e0/collector/collector.go#L16)).
- [x] Change textfile collector defaults.
- [x] Change Go module name.
- [x] Update build automation.
- [x] Change the installer.
- [x] Update contrib/console_templates.
- [x] Update docs.
- [x] Rename repo.

**Comment by Mario-Hofstaetter** [comment]
This there an ETA on this to prepare for?
Since renaming the metrics is quite the breaking change and we are just rolling out the exporter and dashboards.

**Comment by carlpett** [comment]
Hey @Mario-Hofstaetter,
Very good question! There's a bunch of unreleased changes on master (three new collectors!), so I will make sure that is released as 0.12. Then hopefully do the move within the next week, workload permitting.
I have prepared most of the changes, but ran out of time to validate them. Especially the installer requires a bit of care.

If you want to prepare your environment, you could actually set up a metric relabeling in the Prometheus server to switch the metric namespace already with the current versions. Something like this:

```yaml
  - job_name: windows
    static_configs:
    - targets: ['localhost:9182']
    metric_relabel_configs:
    - source_labels: ['__name__']
      target_label: '__name__'
      regex: 'wmi_(.*)'
      replacement: 'windows_$1'
```
