### ISSUE TITLE
kubernetes endpoint

### ISSUE THREAD

**Issue by frederiksf** [prometheus-community/windows_exporter#591]
We are using prometheus with the prometheus operator and the servicemonitor. our k8scluster is dynamic where nodes come and go. How can i create an k8s endpoint on the moment a new node becomes ready? 

I saw on the internet i can create a static endpoint but this is not workable since we use autoscaler.

```
kind: Endpoints
apiVersion: v1
metadata:
 name:  ip-10-2-30-51.eu-central-1.compute.internal
subsets:
 - addresses:
     - ip: 10.2.30.233
   ports: 
	   - name: metrics
       port: 5000
```

Does anybody help this?
