### ISSUE TITLE
Unable to start windows_exporter with a configuration file in the default location

### ISSUE THREAD

**Issue by qmonitoring** [prometheus-community/windows_exporter#660]
Unable to start windows_exporter with a configuration file in the default location

Steps to reproduce:

OS: Win 10 Pro 10.0.19041
User with a Administrator privileges

**First scenario**: Default config

1)Create folder _C:\Program Files\windows_exporter_ with the following files:

windows_exporter-0.15.0-amd64.msi
config.yml

config.yml file content:

```
collectors:
  enabled: service
collector:
  service:
    services-where: "Name='<any_existing_service>'"
log:
  level: warn
```
  
2)Execute the following command in PowerShell (under Administrator)

_msiexec /i C:\Program Files\windows_exporter\windows_exporter-0.15.0-amd64.msi_

Expected result:

The windows_exporter is up and running with parameters from the _C:\Program Files\windows_exporter\config.yml_ file

Actual result:
The windows installer popup like this
![image](https://user-images.githubusercontent.com/74351302/98929625-021a9b00-250e-11eb-9773-983ca6ce95a9.png)

**Second scenario**: Explicitly add a path to the config file in the C:\Program Files\windows_exporter directory

1)Create folder _C:\Program Files\windows_exporter_ with the following files:

windows_exporter-0.15.0-amd64.msi
config.yml

config.yml file content:

```
collectors:
  enabled: service
collector:
  service:
    services-where: "Name='<any_existing_service>'"
log:
  level: warn
```
  
2)Execute the following command in PowerShell (under Administrator)

_msiexec /i C:\Program Files\windows_exporter\windows_exporter-0.15.0-amd64.msi --% EXTRA_FLAGS="--config.file=C:\\Program Files\\windows_exporter\\config.yml"_

Expected result:

The windows_exporter is up and running with parameters from the _C:\Program Files\windows_exporter\config.yml_ file

Actual result:
The windows installer popup like this
![image](https://user-images.githubusercontent.com/74351302/98929857-6178ab00-250e-11eb-8b3e-bc4f661ce05c.png)

**Third scenario**: Explicitly add a path to the config file in the C:\Program Files\windows_exporter directory and locate windows_exporter-0.15.0-amd64.msi installation file in C:\windows_exporter folder

1)Create folder _C:\windows_exporter_ with the following file:

windows_exporter-0.15.0-amd64.msi

Create folder _C:\Program Files\windows_exporter_ with the following file:

config.yml

config.yml file content:

```
collectors:
  enabled: service
collector:
  service:
    services-where: "Name='<any_existing_service>'"
log:
  level: warn
```
  
2)Execute the following command in PowerShell (under Administrator)

_msiexec /i C:\windows_exporter\windows_exporter-0.15.0-amd64.msi --% EXTRA_FLAGS="--config.file=C:\\Program Files\\windows_exporter\\config.yml"_

Expected result:

The windows_exporter is up and running with parameters from the _C:\Program Files\windows_exporter\config.yml_ file

Actual result:
Error popup:
![image](https://user-images.githubusercontent.com/74351302/98930032-a6044680-250e-11eb-9435-27442a804b57.png)

**Fourth scenario**: Explicitly add a path to the config file in the _C:\windows_exporter_ directory

1)Create folder _C:\windows_exporter_ with the following files:

windows_exporter-0.15.0-amd64.msi
config.yml file content:

```
collectors:
  enabled: service
collector:
  service:
    services-where: "Name='<any_existing_service>'"
log:
  level: warn
```
  
3)Execute the following command in PowerShell (under Administrator)

_msiexec /i C:\windows_exporter\windows_exporter-0.15.0-amd64.msi --% EXTRA_FLAGS="--config.file=C:\\windows_exporter\\config.yml"_

Expected result:

windows_exporter is up and running with parameters from the _C:\windows_exporter\config.yml_ file

Actual result:
**The windows_exporter is up and running**

**Question**: How to start windows_exporter with a configuration file in the default location?
