### ISSUE TITLE
Multiple options using config.yml

### ISSUE THREAD

**Issue by MrChips821** [prometheus-community/windows_exporter#664]
Is it possible to specify options to both restrict the services and processes that are collected using the config.yml method?
I'm using the below config but no processes are returned. 

```
collectors:
  enabled: cpu,cs,logical_disk,os,process,net,service,system
collector:
  service:
    services-where: "Name LIKE 'dev%'"   
  process:
    whitelist: "app1.exe|app2.+|app3.+|app4.+"
log:
  level: debug
```

**Comment by breed808** [comment]
Regarding the processes, you may need to omit the `.exe` suffix. I've used the following to get metrics for the `windows_exporter.exe` process:

```yaml
collectors:
  enabled: process
collector:
  process:
    whitelist: windows_exporter
```

Using `whitelist: windows_exporter.exe` caused the exporter to return no process metrics.
