### ISSUE TITLE
[Help] Config file 

### ISSUE THREAD

**Issue by ced455** [prometheus-community/windows_exporter#673]
Hello there 

I am trying to create a config file for the exporter and I need some specific metrics.

As an example in iis i would like to monitor : 

- windows_iis_current_non_anonymous_users
- windows_iis_current_anonymous_users

And nothing else coming from iis

In my config file I wrote :

```
collectors:
  enabled: os,iis,net,cpu,logical_disk 
collector:
  iis:
    iis-where: "Name='windows_iis_current_non_anonymous_users','windows_iis_current_anonymous_users'"
```

But does not look like it work and i cannot find the right doc to refer to.

Could anyone correct my example to my need so i can understand the logic behind this config ?

Thanks

**Comment by breed808** [comment]
Hi @ced455, the config file structure mirrors that of the CLI flags. For the IIS collector, there are the following flags:
```
--collector.iis.site-whitelist
--collector.iis.site-blacklist
--collector.iis.app-whitelist
--collector.iis.app-blacklist
```

These could be represented in a configuration file like so:
```yaml
collectors:
  enabled: os,iis,net,cpu,logical_disk 
collector:
  iis:
    site-whitelist: "my_awesome_iis_site"
```

All of these flags accept Golang regular expressions, which can be tested at https://regex101.com/

In your particular case, you're not able to restrict the metrics returned by the IIS collector, only the sites and/or application pools.

**Comment by ced455** [comment]
Hello @breed808, thank you for your answer !

I am starting to understand the logic there, it is very helpfull thanks ! Where did you find this information ?

A shame, we need to monitor some mssql server but we don't need all of them (the are hundreds available there !)

**Comment by breed808** [comment]
You can find the collector documentation [here](docs/collector.iis.md). The main [README](README.md) has links to the documentation for each collector.

For the [MSSQL collector](docs/collector.mssql.md), you could use `--collectors.mssql.classes-enabled` to limit the exporter metrics.

**Comment by breed808** [comment]
It's also worth noting that Prometheus supports [dropping metrics](https://www.robustperception.io/dropping-metrics-at-scrape-time-with-prometheus) whilst scraping, which may be of use to you.

**Comment by ced455** [comment]
Thank you @breed808 !

**Comment by kylewin** [comment]
@breed808 Morning sir. How can I pass this flag to the config.yaml file ? 
```
Disabled by default, and can be enabled with --collector.process.iis. NOTE: Just plain parameter without true
```
I tried
```
collector:
  process:
  - iis
  and
  process:
   iis: true
```
both are not working. I'd need to see the IIS apps in metric label
