### ISSUE TITLE
windows-exporter config.yml - List of services

### ISSUE THREAD

**Issue by dw-scm** [prometheus-community/windows_exporter#712]
Is it possible to have a list of services instead of 1 or all of them?

collectors:
  enabled: cpu,cs,net,service,os,memory,iis,logical_disk
collector:
  service:
    services-where: "Name='spooler'"
    services-where: "Name='tabletinputservice'"
    services-where: "Name='wmi_exporter'"
    services-where: "Name='power'"
    services-where: "Name='iisadmin'"
    services-where: "Name='msmq'"
log:
  level: warn
telemetry:
   addr: ":9090" 

I tried this but it only picks up the last service mentioned.

Thanks in advanced.

**Comment by breed808** [comment]
Hi @dw-scm this will be due to the multiple `services-where` entries. The exporter will be reading the final entry, discarding the others.You'll need a single WMI filter in the config:

E.G.
```yaml
collectors:
  enabled: cpu,cs,net,service,os,memory,iis,logical_disk
collector:
  service:
    services-where: "Name='spooler' or Name='tabletinputservice' or Name='wmi_exporter' or Name='power' or Name='iisadmin' or Name='msmq'"
log:
  level: warn
telemetry:
  addr: ":9090"
```
