### ISSUE TITLE
No data collected when CPU is overloaded

### ISSUE THREAD

**Issue by a-mazed** [prometheus-community/windows_exporter#724]
Hi team!
Can you please give me an advice how to collect metrics when host's CPU is overloaded?

As you can see in the screenshot below, no data has been collected between the red lines.
The query is 
`100 - (avg by (instance) (irate(windows_cpu_time_total{mode="idle", instance=~"my_host"}[1m])) * 100)`
![image](https://user-images.githubusercontent.com/25726917/107750310-e7cea400-6d2c-11eb-9787-8a0f8b5ebebb.png)

Is this the exporter issue or a problem with my local configuration?

My Prometheus config:

```
  - job_name: 'windows_exporter' 

    scrape_interval: 25s
    scrape_timeout: 20s
```
 
And windows_exporter config:
```
collectors:
  enabled: cpu,cs,logical_disk,net,os,service,system,process,iis
log:
  level: warn
scrape:
  timeout-margin: 0.1
collector:
  service:
    services-where: (NAME = 'windows_exporter') OR (Name = 'W3SVC') OR (Name = 'Redis')
  process:
    whitelist: windows_exporter|w3wp
```
