### ISSUE TITLE
TextFile Directory parameter not working when using config.yml

### ISSUE THREAD

**Issue by PauloFernandoPires** [prometheus-community/windows_exporter#740]
I'm trying to use config.yml to set a custom location for textfile but the application still tries to access default location.

config.yml

```
collectors:
  enabled: cpu,cs,logical_disk,os,service,system,textfile
collector:
  textfile:
    directory: 'c:\temp\test'
  logical_disk:
    volume-whitelist: '\w:'
  service:
    services-where: "Name='whatever'"
log:
  level: warn
```

Output
```
time="2021-03-03T10:00:12-03:00" level=error msg="Error reading textfile collector directory \"C:\\\\Program Files\\\\windows_exporter\\\\textfile_inputs\": open C:\\Program Files\\windows_exporter\\textfile_inputs: The system cannot find the path specified." source="textfile.go:222"
```

Version
```  
windows_exporter, version 0.16.0 (branch: master, revision: f316d81d50738eb0410b0748c5dcdc6874afe95a)
  build user:       appveyor-vm\appveyor@appveyor-vm
  build date:       20210225-10:52:19
  go version:       go1.15.6
  platform:         windows/amd64
```

The application works properly when I use the "--collector.textfile.directory" parameter

**Comment by breed808** [comment]
Hmm, I'm not able to reproduce this with the v0.16.0 version:

```yaml
---
# Note this is not an exhaustive list of all configuration values
collectors:
  enabled: cpu,cs,logical_disk,net,os,service,system,textfile
collector:
  service:
    services-where: Name='windows_exporter'
  textfile:
    directory: 'c:\temp\test'
log:
  level: debug
scrape:
  timeout-margin: 0.5
telemetry:
  addr: ":9182"
  path: /metrics
  max-requests: 5
```

```
PS C:\Users\breed808\Desktop> .\windows_exporter.exe --config.file=example_config.yml
time="2021-03-07T10:25:30+10:00" level=info msg="Loading configuration file: example_config.yml" source="config.go:37"
time="2021-03-07T10:25:30+10:00" level=debug msg="Initializing SWbemServices" source="exporter.go:248"
time="2021-03-07T10:25:31+10:00" level=debug msg="Detected Windows version 6.300000\n" source="collector.go:48"
time="2021-03-07T10:25:31+10:00" level=info msg="Enabled collectors: textfile, cpu, cs, logical_disk, net, os, service, 
system" source="exporter.go:347"
time="2021-03-07T10:25:31+10:00" level=info msg="Starting windows_exporter (version=, branch=, revision=)" source="expor
ter.go:399"
time="2021-03-07T10:25:31+10:00" level=info msg="Build context (go=go1.15.8, user=, date=)" source="exporter.go:400"    
time="2021-03-07T10:25:31+10:00" level=info msg="Starting server on :9182" source="exporter.go:403"
time="2021-03-07T10:25:31+10:00" level=info msg="TLS is disabled." source="gokit_adapter.go:38"
time="2021-03-07T10:25:31+10:00" level=error msg="Failed to start service: The service process could not connect to the 
service controller." source="exporter.go:337"
time="2021-03-07T10:25:49+10:00" level=debug msg="collector cpu succeeded after 0.000000s." source="exporter.go:209"
time="2021-03-07T10:25:49+10:00" level=debug msg="Generated WMI query SELECT * FROM Win32_OperatingSystem" source="wmi.g
o:24"
time="2021-03-07T10:25:49+10:00" level=debug msg="collector net succeeded after 0.000000s." source="exporter.go:209"    
time="2021-03-07T10:25:49+10:00" level=debug msg="Generated WMI query SELECT * FROM Win32_Service WHERE Name='windows_ex
porter'" source="wmi.go:47"
time="2021-03-07T10:25:49+10:00" level=debug msg="Processing file \"c:\\\\temp\\\\test\\\\test.prom\"" source="textfile.
go:232"
time="2021-03-07T10:25:49+10:00" level=debug msg="collector textfile succeeded after 0.004762s." source="exporter.go:209
"
time="2021-03-07T10:25:49+10:00" level=debug msg="Generated WMI query SELECT * FROM Win32_ComputerSystem" source="wmi.go
:24"
time="2021-03-07T10:25:49+10:00" level=debug msg="collector system succeeded after 0.000000s." source="exporter.go:209" 
time="2021-03-07T10:25:49+10:00" level=debug msg="collector logical_disk succeeded after 0.001013s." source="exporter.go
:209"
time="2021-03-07T10:25:49+10:00" level=debug msg="collector os succeeded after 0.066830s." source="exporter.go:209"
time="2021-03-07T10:25:50+10:00" level=debug msg="collector service succeeded after 0.348749s." source="exporter.go:209"
time="2021-03-07T10:25:50+10:00" level=debug msg="collector cs succeeded after 0.361822s." source="exporter.go:209"
```

Could you provide the full output with the log level set to "debug"?
