### ISSUE TITLE
Service Metrics not being exporter

### ISSUE THREAD

**Issue by louij2** [prometheus-community/windows_exporter#757]
Not sure why but on two hosts I am setting up the exporter on, they do not export any service metrics.

![image](https://user-images.githubusercontent.com/2940588/114546411-05e55180-9c55-11eb-978d-cd10e1605fc3.png)

![image](https://user-images.githubusercontent.com/2940588/114546596-3dec9480-9c55-11eb-88f1-b43ab15f28f8.png)

Checked on the :9182/metrics too and see nothing.

**Comment by breed808** [comment]
I've just attempted this on a newly-installed Windows Server 2019 image, but can't reproduce the issue.

config.yml:
```yaml
collectors:
  enabled: cpu,cs,logical_disk,net,os,service,system,textfile,process,iis
collector:
  service:
    services-where: Name='windows_exporter'
log:
  level: debug
scrape:
  timeout-margin: 0.5
telemetry:
  addr: ":9183"
  path: "/metrics"
  max-requests: 5
```

Running windows_exporter v0.16.0:
```
.\windows_exporter.exe --config.file=config.yml
```

![Screenshot_20210418_101822](https://user-images.githubusercontent.com/3103817/115130051-6eef0f80-a02f-11eb-9733-9a4083c7820f.png)

Could you provide the OS version and any debug output from the exporter?
