### ISSUE TITLE
Feature - Improve filters for processes collector

### ISSUE THREAD

**Issue by gillg** [prometheus-community/windows_exporter#855]
Hello,

I would be able to chose dynamicaly process metrics to collect instead / in addition of whitelist, blacklist.

The idea would be to add a filter based on one of the metrics, with a thresold, and a topK process matching.
I don't know what is possible with WMI queries, or if we have to getall metrics then order + slice in go.

Possible config :
```yaml
collectors:
  # Adapt collectors to enable
  enabled: process

collector:
  process:
    filters:
      windows_process_working_set_bytes: 
        # all process above 2g
        min_thresold: 2g
        # only ten first
        limit: 10
      # implicit OR ?
      windows_process_thread_count:
        min_thresold: 300
        limit: 5
```
Any other ideas are welcome... To monitor the CPU, it seems more complicated (not realistic ?) because we only have a CPU total time, except if you are aware of a perfcounter for percentage.

Any idea on the feasability ?
Anyone with some knowlegde on WMI ?
