### ISSUE TITLE
How to detect clock skew or lack of system clock synchronisation

### ISSUE THREAD

**Issue by rdiez** [prometheus-community/windows_exporter#870]
Is there a way to detect clock skew or lack of system clock synchronisation?

The 'time' collector is documented to work only Windows Server 2016 or newer, but I want to detect this condition on normal Windows PCs too.

As a source for inspiration, here are some rules that should do the trick for the Node Exporter (for Linux/Unix hosts):

Host clock skew 
Host clock not synchronising 
https://awesome-prometheus-alerts.grep.to/rules#host-and-hardware

**Comment by breed808** [comment]
`windows_time_computed_time_offset_seconds` from the [time](https://github.com/prometheus-community/windows_exporter/blob/f84f54afdaa215259b443f2d6011c99902a181dd/docs/collector.time.md) collector would be the most suitable metric for this.

I've tested this on a Windows 11 VM, and the metric is updated every 30 minutes. You could use this with `windows_time_ntp_client_time_source_count` to determine if the NTP client is active (0 indicating no NTP sources).

**Comment by rdiez** [comment]
As I stated above, the 'time' collector is documented to work only Windows Server 2016 or newer.

Do you mean then that Windows 11 Pro (non server) also supports the necessary Time Service perflib counters? Or is the documentation wrong, and Windows 10 Home or Pro has them too?

Besides, windows_time_computed_time_offset_seconds is documented as "Absolute time offset between the system clock and the chosen time source, in seconds.". That probably wouldn't work if the system cannot reach any time servers.

I would have thought that windows_time_ntp_client_time_source_count would be a better way. If > 0, the system has found one time source. The question is, if the system synchronises its clock with the domain controller (when the computer has joined a domain), does the domain controller count as an NTP time source?

**Comment by breed808** [comment]
> As I stated above, the 'time' collector is documented to work only Windows Server 2016 or newer.

Apologies, I missed that part of your original post.

> Do you mean then that Windows 11 Pro (non server) also supports the necessary Time Service perflib counters?

Yes, in my case this was with Windows 11 Pro. The note in the documentation was intended for Windows Server (I.E. Windows Server >= 2016 will have the metrics), as most desktop versions of Windows remain untested.

> I would have thought that windows_time_ntp_client_time_source_count would be a better way. If > 0, the system has found one time source. The question is, if the system synchronises its clock with the domain controller (when the computer has joined a domain), does the domain controller count as an NTP time source?

I would assume that yes, a DC will count as an NTP time source.

**Comment by callMe-Root** [comment]
Hello, I have a related problem, I have tried to observe if windows_time_computed_time_offset_seconds is really works as I expected (I wasn't sure if I understood the documentation correctly). 

I've used `Set-Date -Adjust -0:10:0 -DisplayHint Time` ps command to get an alarm with prometheus, however I never get this metric show correctly:

<img width="1768" alt="resim" src="https://user-images.githubusercontent.com/68336965/216036913-25711809-130c-48fb-8638-be053baa5e7a.png">


I confirmed the time difference with `w32tm /stripchart /computer:foo`, the output is like this:

```

PS C:\Users\baruser> w32tm /stripchart /computer:foo.my.domain
Tracking foo.my.domain [x.y.z.t:123].
The current time is 1.02.2023 14:34:59.
14:34:59, d:+00.0002322s o:+600.0106644s  [                           |                          @]
14:35:01, d:+00.0003498s o:+600.0107934s  [                           |                          @]
```

Both my ntp client and server are server 2019, what am i missing? My windows_exporter version is 0.20.0

**Comment by breed808** [comment]
@callMe-Root is Perflib returning the same metric values? You could watch with:

```powershell
while ($true) {
    Get-Counter -Counter '\Windows Time Service\Computed Time Offset'
    Start-Sleep -Seconds 1
}
```

**Comment by rdiez** [comment]
A few days ago, the CMOS battery died in one of my Windows PCs. I was getting weird TLS certificate encryption errors, and it took a while for me to realise that the realtime clock was very wrong (years in the past).

So I decided to look into this issue again. I have managed to detect time drift with these alerts:

```
- alert: TimeDriftUnix
  expr: abs( node_time_seconds - timestamp( node_time_seconds ) ) > 2
  for: 1m
  labels:
    severity: Warning
  annotations:
    summary: "Time drift detected"
    description: "The time drift on {{ $labels.instance }} is {{ $value }} seconds."

- alert: TimeDriftWindows
  expr: abs( windows_os_time - timestamp( windows_os_time ) ) > 2
  for: 1m
  labels:
    severity: Warning
  annotations:
    summary: "Time drift detected"
    description: "The time drift on {{ $labels.instance }} is {{ $value }} seconds."
```

There is some confusion on Windows about metric `windows_os_time`. I could not find which Windows Exporter collector generates it, so it may be called something else nowadays. You could also use `windows_time_current_timestamp_seconds` from the `time` collector.
